// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTA8qJIi2wWCkSWMfpcp0ssTULE7UPKM',
    appId: '1:409848872590:web:12e8d976319e06e7ee53df',
    messagingSenderId: '409848872590',
    projectId: 'mini-todo-list-flutter',
    authDomain: 'mini-todo-list-flutter.firebaseapp.com',
    storageBucket: 'mini-todo-list-flutter.firebasestorage.app',
    measurementId: 'G-L1EVJ8EMDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3gUQdX8RGWFPxMvEuUzrJkXnFGQOXws',
    appId: '1:409848872590:android:50affb624b3c31daee53df',
    messagingSenderId: '409848872590',
    projectId: 'mini-todo-list-flutter',
    storageBucket: 'mini-todo-list-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCep7yxRuqPZ1-X9jVWO_FQYnkAI3xAAeE',
    appId: '1:409848872590:ios:8b611f5f35858200ee53df',
    messagingSenderId: '409848872590',
    projectId: 'mini-todo-list-flutter',
    storageBucket: 'mini-todo-list-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectAub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCep7yxRuqPZ1-X9jVWO_FQYnkAI3xAAeE',
    appId: '1:409848872590:ios:8b611f5f35858200ee53df',
    messagingSenderId: '409848872590',
    projectId: 'mini-todo-list-flutter',
    storageBucket: 'mini-todo-list-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectAub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPTA8qJIi2wWCkSWMfpcp0ssTULE7UPKM',
    appId: '1:409848872590:web:e498c350a7f11ba2ee53df',
    messagingSenderId: '409848872590',
    projectId: 'mini-todo-list-flutter',
    authDomain: 'mini-todo-list-flutter.firebaseapp.com',
    storageBucket: 'mini-todo-list-flutter.firebasestorage.app',
    measurementId: 'G-55QGG7ZVL7',
  );
}
